
server:
  port: 7070
  
  
spring:
  cloud:
    stream:
      bindings:
         highValue:
           destination: premium
         normalValue:
           destination: normal    
           
           