server:
  port: 2020
  
spring:  application:    name: account-client-service

eureka:  client:
      fetch-registry: true
    register-with-eureka: true
    service-url:      defaultZone: http://localhost:8761/eureka   
      
